export const GET_DOCLIST_REQUEST = 'table/GET_DOCLIST_REQUEST';
export const GET_DOCWITHLOBSSEGMENTS_REQUEST = 'table/GET_DOCWITHLOBSSEGMENTS_REQUEST';
export const GET_METRICSWITHDOCUMENTS_REQUEST = 'table/GET_METRICSWITHDOCUMENTS_REQUEST';
export const SET_DOCLIST_REQUEST = 'table/SET_DOCLIST_REQUEST';
export const SET_DOCWITHLOBSSEGMENTS_REQUEST = 'table/SET_DOCWITHLOBSSEGMENTS_REQUEST';
export const SET_METRICSWITHDOCUMENTS_REQUEST = 'table/SET_METRICSWITHDOCUMENTS_REQUEST';
